# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InPowered', '0002_auto_20160906_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedpage',
            name='url',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
